#!usr/bin/python3

import scapy.all as scapy

def scapy(ip):

    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_packet = broadcast/arp_request_packet
    answered_list = scapy.srp(arp_request_packet,timeout=1,verbose=false)[0]

    
    print("IP\t\t\tMAC address \n -------")
    clients_list=[]

    for element in answered_list:
        client_dict = {"ip":element[1].psrc, "mac":element[1].hwsrc}
        clients_list = append(clients_dict)
        print(element[1].psrc +"\t\t"+ element[1].hwsrc)

    print(clients_list)
        

scan("10.20.2.1")