#!usr/bin/python3

import scapy.all as scapy

import argparse

def get_arguments():
    
    parser = argparse.ArgumentParser()
    parser.add_argument("-t","--target",dest = "target",help = "target ip/ip range")
    options = parser.parse_args()
    return options


def scapy(ip):

    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_packet = broadcast/arp_request_packet
    answered_list = scapy.srp(arp_request_packet,timeout=1,verbose=false)[0]

    
    
    clients_list=[]

    for element in answered_list:
        client_dict = {"ip":element[1].psrc, "mac":element[1].hwsrc}
        clients_list = append(clients_dict)
    return clients_list

def print_result(results_list):

    print("IP\t\t\tMAC address \n -------")

    for client in results_list:
        print(client["ip"] + "\t\t\t" + client["mac"])



options = get_arguments()
scan_result = scan(options.target)
print_result = scan_result
